using System.Globalization;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using Markdig;
using Markdig.Syntax;
using Markdig.Syntax.Inlines;

namespace Pavillon46.Api.Services;

/// <summary>
/// Renders a newsletter body — authored as Markdown in the admin editor, or
/// generated by the LLM in <see cref="NewsletterAiService"/> — into the two
/// MIME parts a newsletter email needs. The admin preview and the member
/// portal both run the body through react-markdown; this renderer is the
/// email-side equivalent so all three surfaces agree.
/// </summary>
public interface INewsletterEmailRenderer
{
    /// <summary>Email-safe, inline-styled HTML for the text/html part. Returns a
    /// fragment (no html/head/body), meant to be dropped into the newsletter
    /// shell where the body paragraphs go.</summary>
    string RenderHtmlFragment(string markdown);

    /// <summary>Readable plain text for the text/plain part. Never contains
    /// markup or HTML entities.</summary>
    string RenderPlainText(string markdown);
}

/// <summary>
/// Markdown → email renderer for newsletter bodies.
///
/// SECURITY — this class is the last line of defence before SendGrid.
/// The body it renders is written by an admin or produced by an LLM, and the
/// output is blasted to every member's inbox, so it is treated as untrusted
/// input throughout:
///
///  * The Markdig pipeline is built with <c>DisableHtml()</c>, so raw HTML in
///    the body is never parsed as markup — it stays literal text and is
///    HTML-encoded on the way out. An admin cannot smuggle in a &lt;script&gt;,
///    an &lt;img&gt; tracking pixel, or a hidden iframe.
///  * The HTML is not produced by Markdig's HtmlRenderer. This class walks the
///    parsed AST and emits its own tags from a fixed allow-list (p, h2, h3,
///    strong, em, a, ul, ol, li, blockquote, br). Anything outside that list is
///    dropped rather than passed through, so a future pipeline change cannot
///    silently widen the output.
///  * Every href must be an absolute http, https or mailto URL
///    (see <see cref="TryNormalizeUrl"/>). javascript:, data:, vbscript: and
///    file: links, and URLs carrying control characters, are refused — the link
///    text survives, the link does not.
///  * All text and all attribute values go through
///    <see cref="WebUtility.HtmlEncode"/>.
///
/// Recursion is depth-capped so an adversarial body (deeply nested quotes or
/// lists) cannot exhaust the stack of a request thread.
///
/// Note on SendGrid: substitutions (-titleHtml-, -greetingHtml-,
/// -unsubscribeUrl-, …) are a literal string replace performed on the body
/// *after* rendering. This renderer therefore never emits those tokens itself.
///
/// The class is stateless and the Markdig pipeline is immutable once built, so
/// a single instance is safe to share — register it as a singleton.
/// </summary>
public sealed class NewsletterEmailRenderer : INewsletterEmailRenderer
{
    // DisableHtml() drops the HTML block parser and clears
    // AutolinkInlineParser.EnableHtmlParsing, so raw tags are never turned into
    // markup. No extensions are enabled on purpose: plain CommonMark keeps the
    // email in step with the admin preview and the member portal, both of which
    // use react-markdown with its default (CommonMark) plugin set.
    private static readonly MarkdownPipeline Pipeline = new MarkdownPipelineBuilder()
        .DisableHtml()
        .Build();

    private static readonly HashSet<string> AllowedSchemes =
        new(StringComparer.OrdinalIgnoreCase) { "http", "https", "mailto" };

    // Guards against stack exhaustion from pathological nesting.
    private const int MaxDepth = 24;

    // Inline styles matching the transactional palette in
    // NewsletterSender.BuildHtml. Email clients strip <style> blocks and
    // <head>, so every element carries its own style attribute; list styles are
    // repeated on <li> because Outlook does not inherit them from <ul>/<ol>.
    private const string StyleParagraph = "margin:0 0 18px 0;font-size:16px;color:#3a4a42;line-height:1.7;";
    private const string StyleH2 = "margin:28px 0 12px 0;color:#265640;font-family:Jost,'Helvetica Neue',Arial,sans-serif;font-size:20px;font-weight:400;line-height:1.3;";
    private const string StyleH3 = "margin:22px 0 10px 0;color:#265640;font-family:Jost,'Helvetica Neue',Arial,sans-serif;font-size:17px;font-weight:500;line-height:1.35;";
    private const string StyleList = "margin:0 0 18px 0;padding:0 0 0 22px;font-size:16px;color:#3a4a42;line-height:1.7;";
    private const string StyleListItem = "margin:0 0 8px 0;font-size:16px;color:#3a4a42;line-height:1.7;";
    private const string StyleQuote = "margin:0 0 18px 0;padding:4px 0 4px 16px;border-left:3px solid #265640;color:#3a4a42;font-size:16px;line-height:1.7;font-style:italic;";
    private const string StyleLink = "color:#265640;text-decoration:underline;";
    private const string StyleStrong = "font-weight:600;";
    private const string StyleEmphasis = "font-style:italic;";

    private static readonly Regex BlankLineRuns = new(@"\n{3,}", RegexOptions.Compiled);
    private static readonly Regex TrailingSpaces = new(@"[ \t]+\n", RegexOptions.Compiled);

    public string RenderHtmlFragment(string markdown)
    {
        if (string.IsNullOrWhiteSpace(markdown)) return string.Empty;

        MarkdownDocument document;
        try
        {
            document = Markdown.Parse(markdown, Pipeline);
        }
        catch (Exception)
        {
            // Markdig throws on pathologically nested input (its own depth
            // guard). This renderer runs inside a bulk send, so it degrades
            // instead of taking a 1000-recipient batch down with it: the body
            // goes out as HTML-encoded plain paragraphs, unformatted but safe
            // and complete.
            return RenderFallbackHtml(markdown);
        }

        var sb = new StringBuilder(markdown.Length * 2);
        WriteBlocksHtml(document, sb, 0);
        return sb.ToString();
    }

    public string RenderPlainText(string markdown)
    {
        if (string.IsNullOrWhiteSpace(markdown)) return string.Empty;

        MarkdownDocument document;
        try
        {
            document = Markdown.Parse(markdown, Pipeline);
        }
        catch (Exception)
        {
            // Same fallback contract as RenderHtmlFragment: never throw. The
            // decode turns any literal "&amp;" into "&" — the text/plain part
            // must not carry HTML entities.
            return NormalizeText(WebUtility.HtmlDecode(markdown));
        }

        var sb = new StringBuilder(markdown.Length + 32);
        WriteBlocksText(document, sb, 0, string.Empty);
        return NormalizeText(sb.ToString());
    }

    private static string NormalizeText(string text)
    {
        text = text.Replace("\r\n", "\n").Replace("\r", "\n");
        text = TrailingSpaces.Replace(text, "\n");
        text = BlankLineRuns.Replace(text, "\n\n");
        return text.Trim();
    }

    private static string RenderFallbackHtml(string markdown)
    {
        var sb = new StringBuilder(markdown.Length * 2);
        foreach (var chunk in markdown.Split(
                     new[] { "\r\n\r\n", "\n\n" }, StringSplitOptions.RemoveEmptyEntries))
        {
            var trimmed = chunk.Trim();
            if (trimmed.Length == 0) continue;
            sb.Append("<p style=\"").Append(StyleParagraph).Append("\">")
              .Append(WebUtility.HtmlEncode(trimmed))
              .Append("</p>");
        }
        return sb.ToString();
    }

    // ---------------------------------------------------------------- HTML

    /// <param name="unwrapFirstParagraph">Used for list items: in a tight list
    /// the item's first paragraph is emitted without a &lt;p&gt; wrapper, which
    /// is what CommonMark renderers do.</param>
    private static void WriteBlocksHtml(
        ContainerBlock container, StringBuilder sb, int depth, bool unwrapFirstParagraph = false)
    {
        if (depth > MaxDepth) return;

        var unwrapped = false;
        foreach (var block in container)
        {
            switch (block)
            {
                case ParagraphBlock paragraph:
                    if (unwrapFirstParagraph && !unwrapped)
                    {
                        WriteInlinesHtml(paragraph.Inline, sb, depth + 1);
                        unwrapped = true;
                    }
                    else
                    {
                        // A block whose only content was dropped (an image-only
                        // paragraph, say) is removed entirely rather than left
                        // as an empty element pushing 18px of dead space.
                        var open = sb.Length;
                        sb.Append("<p style=\"").Append(StyleParagraph).Append("\">");
                        var contentStart = sb.Length;
                        WriteInlinesHtml(paragraph.Inline, sb, depth + 1);
                        if (sb.Length == contentStart) sb.Length = open;
                        else sb.Append("</p>");
                    }
                    break;

                case HeadingBlock heading:
                {
                    // Never h1: the newsletter title already owns the h1 in the
                    // email shell. A level-1 heading in the body is demoted to
                    // h2 rather than dropped, so the admin never loses copy.
                    var isH2 = heading.Level <= 2;
                    var tag = isH2 ? "h2" : "h3";
                    var open = sb.Length;
                    sb.Append('<').Append(tag).Append(" style=\"").Append(isH2 ? StyleH2 : StyleH3).Append("\">");
                    var contentStart = sb.Length;
                    WriteInlinesHtml(heading.Inline, sb, depth + 1);
                    if (sb.Length == contentStart) sb.Length = open;
                    else sb.Append("</").Append(tag).Append('>');
                    break;
                }

                case ListBlock list:
                    WriteListHtml(list, sb, depth + 1);
                    break;

                case QuoteBlock quote:
                    sb.Append("<blockquote style=\"").Append(StyleQuote).Append("\">");
                    WriteBlocksHtml(quote, sb, depth + 1);
                    sb.Append("</blockquote>");
                    break;

                // Everything else is outside the supported subset and is
                // dropped: code blocks, thematic breaks, tables, raw HTML
                // blocks, link reference definitions.
                default:
                    break;
            }
        }
    }

    private static void WriteListHtml(ListBlock list, StringBuilder sb, int depth)
    {
        if (depth > MaxDepth) return;

        var ordered = list.IsOrdered;
        sb.Append(ordered ? "<ol" : "<ul").Append(" style=\"").Append(StyleList).Append('"');
        if (ordered
            && int.TryParse(list.OrderedStart, NumberStyles.Integer, CultureInfo.InvariantCulture, out var start)
            && start > 0
            && start != 1)
        {
            sb.Append(" start=\"").Append(start.ToString(CultureInfo.InvariantCulture)).Append('"');
        }
        sb.Append('>');

        foreach (var child in list)
        {
            if (child is not ListItemBlock item) continue;
            sb.Append("<li style=\"").Append(StyleListItem).Append("\">");
            WriteBlocksHtml(item, sb, depth + 1, unwrapFirstParagraph: !list.IsLoose);
            sb.Append("</li>");
        }

        sb.Append(ordered ? "</ol>" : "</ul>");
    }

    private static void WriteInlinesHtml(ContainerInline? container, StringBuilder sb, int depth)
    {
        if (container is null || depth > MaxDepth) return;

        var inline = container.FirstChild;
        while (inline is not null)
        {
            switch (inline)
            {
                case LiteralInline literal:
                    sb.Append(WebUtility.HtmlEncode(literal.Content.ToString()));
                    break;

                case CodeInline code:
                    // Inline code is outside the subset: keep the text, drop the
                    // <code> markup, so no copy is lost.
                    sb.Append(WebUtility.HtmlEncode(code.Content ?? string.Empty));
                    break;

                case EmphasisInline emphasis:
                {
                    var strong = emphasis.DelimiterCount >= 2;
                    sb.Append(strong ? "<strong style=\"" : "<em style=\"")
                      .Append(strong ? StyleStrong : StyleEmphasis)
                      .Append("\">");
                    WriteInlinesHtml(emphasis, sb, depth + 1);
                    sb.Append(strong ? "</strong>" : "</em>");
                    break;
                }

                case LinkInline link:
                    // Images are outside the subset — the newsletter has its own
                    // cover image slot, and an arbitrary remote <img> is exactly
                    // the tracking pixel this renderer exists to refuse.
                    if (link.IsImage) break;
                    if (TryNormalizeUrl(link.Url, out var href))
                    {
                        sb.Append("<a href=\"").Append(WebUtility.HtmlEncode(href))
                          .Append("\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"")
                          .Append(StyleLink).Append("\">");
                        WriteInlinesHtml(link, sb, depth + 1);
                        sb.Append("</a>");
                    }
                    else
                    {
                        // Refused scheme: emit the label as plain text.
                        WriteInlinesHtml(link, sb, depth + 1);
                    }
                    break;

                case AutolinkInline autolink:
                {
                    var target = autolink.IsEmail ? "mailto:" + autolink.Url : autolink.Url;
                    var label = WebUtility.HtmlEncode(autolink.Url);
                    if (TryNormalizeUrl(target, out var autoHref))
                    {
                        sb.Append("<a href=\"").Append(WebUtility.HtmlEncode(autoHref))
                          .Append("\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"")
                          .Append(StyleLink).Append("\">").Append(label).Append("</a>");
                    }
                    else
                    {
                        sb.Append(label);
                    }
                    break;
                }

                case LineBreakInline lineBreak:
                    // Soft breaks collapse to a space, matching react-markdown's
                    // default; only an explicit hard break becomes a <br />.
                    sb.Append(lineBreak.IsHard ? "<br />" : " ");
                    break;

                case HtmlEntityInline entity:
                    sb.Append(WebUtility.HtmlEncode(entity.Transcoded.ToString()));
                    break;

                // Any other container (e.g. a delimiter wrapper) contributes its
                // children only.
                case ContainerInline nested:
                    WriteInlinesHtml(nested, sb, depth + 1);
                    break;

                // HtmlInline and anything else: dropped. DisableHtml() means we
                // should never see raw HTML here; this is the second lock.
                default:
                    break;
            }

            inline = inline.NextSibling;
        }
    }

    // ---------------------------------------------------------- Plain text

    private static void WriteBlocksText(
        ContainerBlock container, StringBuilder sb, int depth, string indent, bool unwrapFirstParagraph = false)
    {
        if (depth > MaxDepth) return;

        var unwrapped = false;
        foreach (var block in container)
        {
            // A list item writes its bullet and then calls back in here. If the
            // item's first block cannot continue that bullet line (a nested list,
            // say), close the line first.
            if (unwrapFirstParagraph && !unwrapped && block is not ParagraphBlock)
            {
                sb.Append('\n');
                unwrapped = true;
            }

            switch (block)
            {
                case ParagraphBlock paragraph:
                    if (unwrapFirstParagraph && !unwrapped)
                    {
                        WriteInlinesText(paragraph.Inline, sb, depth + 1);
                        sb.Append('\n');
                        unwrapped = true;
                    }
                    else
                    {
                        sb.Append(indent);
                        WriteInlinesText(paragraph.Inline, sb, depth + 1);
                        sb.Append("\n\n");
                    }
                    break;

                case HeadingBlock heading:
                    sb.Append(indent);
                    WriteInlinesText(heading.Inline, sb, depth + 1);
                    sb.Append("\n\n");
                    break;

                case ListBlock list:
                    WriteListText(list, sb, depth + 1, indent);
                    break;

                case QuoteBlock quote:
                    WriteBlocksText(quote, sb, depth + 1, indent);
                    break;

                default:
                    break;
            }
        }
    }

    private static void WriteListText(ListBlock list, StringBuilder sb, int depth, string indent)
    {
        if (depth > MaxDepth) return;

        var ordered = list.IsOrdered;
        var number = 1;
        if (ordered
            && int.TryParse(list.OrderedStart, NumberStyles.Integer, CultureInfo.InvariantCulture, out var start)
            && start > 0)
        {
            number = start;
        }

        foreach (var child in list)
        {
            if (child is not ListItemBlock item) continue;
            sb.Append(indent);
            // Unordered items get the em-dash bullet; ordered items keep their
            // number, because "step 3 of 4" is meaningless as a bullet.
            sb.Append(ordered ? number.ToString(CultureInfo.InvariantCulture) + ". " : "— ");
            number++;
            WriteBlocksText(item, sb, depth + 1, indent + "  ", unwrapFirstParagraph: true);

            // An empty item writes nothing at all; keep one bullet per line.
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n') sb.Append('\n');
        }

        sb.Append('\n');
    }

    private static void WriteInlinesText(ContainerInline? container, StringBuilder sb, int depth)
    {
        if (container is null || depth > MaxDepth) return;

        var inline = container.FirstChild;
        while (inline is not null)
        {
            switch (inline)
            {
                case LiteralInline literal:
                    sb.Append(literal.Content.ToString());
                    break;

                case CodeInline code:
                    sb.Append(code.Content ?? string.Empty);
                    break;

                // Emphasis markers are dropped; only the text remains.
                case EmphasisInline emphasis:
                    WriteInlinesText(emphasis, sb, depth + 1);
                    break;

                case LinkInline link:
                {
                    if (link.IsImage) break;
                    var labelStart = sb.Length;
                    WriteInlinesText(link, sb, depth + 1);
                    if (!TryNormalizeUrl(link.Url, out var url)) break;

                    // "(info@pavillon46.ch)" reads better than
                    // "(mailto:info@pavillon46.ch)" in a text/plain part.
                    var shown = url.StartsWith("mailto:", StringComparison.OrdinalIgnoreCase)
                        ? url["mailto:".Length..]
                        : url;

                    var label = sb.ToString(labelStart, sb.Length - labelStart).Trim();
                    if (label.Length == 0)
                    {
                        // Nothing to label the link with: show the URL alone.
                        sb.Length = labelStart;
                        sb.Append(shown);
                    }
                    else if (!string.Equals(label, shown, StringComparison.OrdinalIgnoreCase))
                    {
                        sb.Append(" (").Append(shown).Append(')');
                    }
                    break;
                }

                case AutolinkInline autolink:
                    sb.Append(autolink.Url);
                    break;

                case LineBreakInline lineBreak:
                    sb.Append(lineBreak.IsHard ? '\n' : ' ');
                    break;

                // Entities become the character they stand for — the text/plain
                // part must never contain "&amp;".
                case HtmlEntityInline entity:
                    sb.Append(entity.Transcoded.ToString());
                    break;

                case ContainerInline nested:
                    WriteInlinesText(nested, sb, depth + 1);
                    break;

                default:
                    break;
            }

            inline = inline.NextSibling;
        }
    }

    // -------------------------------------------------------------- Links

    /// <summary>
    /// Fail-closed URL check for anything that becomes an href. Only absolute
    /// http, https and mailto URLs pass. This is what stops
    /// <c>[click](javascript:…)</c> — and its obfuscated cousins, since Markdig
    /// has already decoded entities in the destination by the time we see it —
    /// from reaching a member's mail client. Relative and fragment-only URLs are
    /// refused too: they cannot resolve from an inbox anyway.
    /// </summary>
    private static bool TryNormalizeUrl(string? url, out string normalized)
    {
        normalized = string.Empty;
        if (string.IsNullOrWhiteSpace(url)) return false;

        var candidate = url.Trim();

        // Control characters are how "java\nscript:" and header-splitting
        // attempts are smuggled past a naive scheme check.
        foreach (var ch in candidate)
        {
            if (char.IsControl(ch)) return false;
        }

        if (!Uri.TryCreate(candidate, UriKind.Absolute, out var uri)) return false;
        if (!AllowedSchemes.Contains(uri.Scheme)) return false;

        normalized = candidate;
        return true;
    }
}
